name = "bb-taxi-platform"
compatibility_date = "2024-01-15"

# Pages build output directory
pages_build_output_dir = "cloudflare-dist"

# Environment Variables for production
[env.production.vars]
NODE_ENV = "production"
JWT_SECRET = "your-production-jwt-secret"
GOVERNMENT_API_URL = "https://api.government.be/taxi"
GOVERNMENT_API_KEY = "your-government-api-key"

# Build configuration for Pages
[build]
command = "npm run build:cloudflare"
destination = "cloudflare-dist"

# Function Routes
[[routes]]
pattern = "/api/taxi-meter/*"
zone_name = "bb-taxi-platform.pages.dev"

[[routes]]
pattern = "/api/drivers/*"
zone_name = "bb-taxi-platform.pages.dev"

[[routes]]
pattern = "/api/bookings/*"
zone_name = "bb-taxi-platform.pages.dev" 